In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\monika\OneDrive\Desktop\flipkart_sales_enriched.csv")

In [3]:
df.head()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,Profit (INR),Discount %,Customer Segment,Region
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5,September,2024,19627.824,11,Online,West
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9,December,2024,10204.680,24,Wholesale,North
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4,May,2024,8873.752,19,Online,South
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2,November,2024,6531.562,15,Online,North
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1,December,2024,15954.048,12,Retail,North

In [4]:
df.tail()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,Profit (INR),Discount %,Customer Segment,Region
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0,January,2025,17397.486,28,Wholesale,West
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4,December,2024,13119.804,23,Wholesale,North
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1,July,2024,8168.160,11,Retail,West
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2,October,2024,27793.432,7,Wholesale,East
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6,March,2024,13358.496,19,Wholesale,East

In [5]:
df.shape

(1000, 15)

In [6]:
df.columns

Index(['Order ID', 'Product Name', 'Category', 'Price (INR)', 'Quantity Sold',
       'Total Sales (INR)', 'Order Date', 'Payment Method', 'Customer Rating',
       'Month', 'Year', 'Profit (INR)', 'Discount %', 'Customer Segment',
       'Region'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   str
 1   Product Name       1000 non-null   str
 2   Category           1000 non-null   str
 3   Price (INR)        1000 non-null   float64
 4   Quantity Sold      1000 non-null   int64
 5   Total Sales (INR)  1000 non-null   float64
 6   Order Date         1000 non-null   str
 7   Payment Method     1000 non-null   str
 8   Customer Rating    1000 non-null   float64
 9   Month              1000 non-null   str
 10  Year               1000 non-null   int64
 11  Profit (INR)       1000 non-null   float64
 12  Discount %         1000 non-null   int64
 13  Customer Segment   1000 non-null   str
 14  Region             1000 non-null   str
dtypes: float64(4), int64(3), str(8)
memory usage: 117.3 KB

In [9]:
df.describe()

,Price (INR),Quantity Sold,Total Sales (INR),Customer Rating,Year,Profit (INR),Discount %
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,24520.258260,3.097000,75213.112740,3.011100,2024.103000,15042.622548,17.699000
std,14187.611227,1.410525,59457.598352,1.145408,0.304111,11891.519670,7.847801
min,139.850000,1.000000,419.550000,1.000000,2024.000000,83.910000,5.000000
25%,12378.905000,2.000000,28581.765000,2.000000,2024.000000,5716.353000,11.000000
50%,24650.015000,3.000000,57358.300000,3.100000,2024.000000,11471.660000,18.000000
75%,35981.925000,4.000000,110618.595000,4.000000,2024.000000,22123.719000,25.000000
max,49911.750000,5.000000,243903.900000,5.000000,2025.000000,48780.780000,30.000000

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum()

Order ID             0
Product Name         0
Category             0
Price (INR)          0
Quantity Sold        0
Total Sales (INR)    0
Order Date           0
Payment Method       0
Customer Rating      0
Month                0
Year                 0
Profit (INR)         0
Discount %           0
Customer Segment     0
Region               0
dtype: int64

In [12]:
df = df.drop_duplicates()

In [13]:
df.dtypes

Order ID                 str
Product Name             str
Category                 str
Price (INR)          float64
Quantity Sold          int64
Total Sales (INR)    float64
Order Date               str
Payment Method           str
Customer Rating      float64
Month                    str
Year                   int64
Profit (INR)         float64
Discount %             int64
Customer Segment         str
Region                   str
dtype: object

In [14]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   str
 1   Product Name       1000 non-null   str
 2   Category           1000 non-null   str
 3   Price (INR)        1000 non-null   float64
 4   Quantity Sold      1000 non-null   int64
 5   Total Sales (INR)  1000 non-null   float64
 6   Order Date         1000 non-null   datetime64[us]
 7   Payment Method     1000 non-null   str
 8   Customer Rating    1000 non-null   float64
 9   Month              1000 non-null   str
 10  Year               1000 non-null   int64
 11  Profit (INR)       1000 non-null   float64
 12  Discount %         1000 non-null   int64
 13  Customer Segment   1000 non-null   str
 14  Region             1000 non-null   str
dtypes: datetime64[us](1), float64(4), int64(3), str(7)
memory usage: 117.3 KB

In [16]:
df["Day"] = df["Order Date"].dt.day

df["Month Name"] = df["Order Date"].dt.month_name()

df["Weekday"] = df["Order Date"].dt.day_name()

In [17]:
df["Category"].unique()

<StringArray>
['Books', 'Clothing', 'Beauty', 'Electronics', 'Home & Kitchen']
Length: 5, dtype: str

In [18]:
df["Region"].unique()

<StringArray>
['West', 'North', 'South', 'East']
Length: 4, dtype: str

In [19]:
df["Payment Method"].unique()

<StringArray>
['Debit Card', 'UPI', 'Wallet', 'COD', 'Credit Card', 'Net Banking']
Length: 6, dtype: str

In [20]:
df["Category"].value_counts()

Category
Electronics       217
Books             209
Home & Kitchen    193
Beauty            192
Clothing          189
Name: count, dtype: int64

In [21]:
df["Region"].value_counts()

Region
South    269
North    259
West     246
East     226
Name: count, dtype: int64

In [22]:
df["Payment Method"].value_counts()

Payment Method
UPI            176
Wallet         172
Debit Card     171
COD            169
Net Banking    166
Credit Card    146
Name: count, dtype: int64

In [23]:
df.describe()

,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Customer Rating,Year,Profit (INR),Discount %,Day
count,1000.000000,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,24520.258260,3.097000,75213.112740,2024-08-09 06:44:38.400000,3.011100,2024.103000,15042.622548,17.699000,15.597000
min,139.850000,1.000000,419.550000,2024-02-12 00:00:00,1.000000,2024.000000,83.910000,5.000000,1.000000
25%,12378.905000,2.000000,28581.765000,2024-05-14 00:00:00,2.000000,2024.000000,5716.353000,11.000000,8.000000
50%,24650.015000,3.000000,57358.300000,2024-08-06 12:00:00,3.100000,2024.000000,11471.660000,18.000000,15.000000
75%,35981.925000,4.000000,110618.595000,2024-11-05 00:00:00,4.000000,2024.000000,22123.719000,25.000000,23.000000
max,49911.750000,5.000000,243903.900000,2025-02-09 00:00:00,5.000000,2025.000000,48780.780000,30.000000,31.000000
std,14187.611227,1.410525,59457.598352,NaN,1.145408,0.304111,11891.519670,7.847801,8.866183

In [24]:
df.nlargest(10,"Total Sales (INR)")

df.nsmallest(10,"Total Sales (INR)")

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,Profit (INR),Discount %,Customer Segment,Region,Day,Month Name,Weekday
736,ORD00737,Hair Dryer,Beauty,139.85,3,419.55,2024-09-14,UPI,2.0,September,2024,83.910,10,Retail,South,14,September,Saturday
536,ORD00537,Educational Book,Books,492.53,1,492.53,2024-04-15,Credit Card,4.4,April,2024,98.506,26,Wholesale,South,15,April,Monday
950,ORD00951,T-Shirt,Clothing,959.63,1,959.63,2024-11-21,Wallet,1.6,November,2024,191.926,26,Retail,West,21,November,Thursday
894,ORD00895,Tablet,Electronics,1002.29,1,1002.29,2025-01-08,UPI,1.4,January,2025,200.458,23,Wholesale,West,8,January,Wednesday
522,ORD00523,Cookware Set,Home & Kitchen,218.58,5,1092.90,2024-04-20,Wallet,4.8,April,2024,218.580,9,Wholesale,West,20,April,Saturday
289,ORD00290,Mixer Grinder,Home & Kitchen,464.18,3,1392.54,2024-08-02,Debit Card,4.1,August,2024,278.508,24,Retail,North,2,August,Friday
458,ORD00459,Sofa Cover,Home & Kitchen,1549.63,1,1549.63,2024-11-27,COD,3.0,November,2024,309.926,25,Retail,North,27,November,Wednesday
937,ORD00938,Fiction Novel,Books,540.63,3,1621.89,2024-04-12,COD,3.5,April,2024,324.378,8,Online,South,12,April,Friday
402,ORD00403,Comic Book,Books,904.29,2,1808.58,2024-05-01,Debit Card,3.5,May,2024,361.716,6,Online,West,1,May,Wednesday
591,ORD00592,Perfume,Beauty,462.00,4,1848.00,2024-06-18,COD,3.4,June,2024,369.600,11,Retail,East,18,June,Tuesday

In [25]:
df.groupby("Product Name")["Quantity Sold"].sum().sort_values(ascending=False).head(10)

Product Name
Educational Book    188
Laptop              156
Table Lamp          141
Fiction Novel       138
Smartwatch          137
Headphones          135
Lipstick            134
Jeans               132
T-Shirt             131
Sneakers            125
Name: Quantity Sold, dtype: int64

In [26]:
df.groupby("Product Name")["Total Sales (INR)"].sum().sort_values(ascending=False).head(10)

Product Name
Educational Book    4522055.35
Laptop              4132783.72
Table Lamp          3986691.68
Headphones          3722765.27
Jeans               3685259.60
Smartwatch          3680177.80
Face Cream          3646816.97
Perfume             3266905.75
Fiction Novel       3172999.91
Jacket              3161049.05
Name: Total Sales (INR), dtype: float64

In [27]:
df.groupby("Category")["Profit (INR)"].sum().sort_values(ascending=False)

Category
Electronics       3461434.614
Clothing          3022877.372
Books             2957151.930
Beauty            2936116.810
Home & Kitchen    2665041.822
Name: Profit (INR), dtype: float64

In [28]:
df.groupby("Region")["Total Sales (INR)"].sum().sort_values(ascending=False)

Region
North    20289991.87
South    19862508.71
West     18392767.90
East     16667844.26
Name: Total Sales (INR), dtype: float64

In [29]:
df.groupby("Category")["Customer Rating"].mean().sort_values(ascending=False)

Category
Home & Kitchen    3.138860
Books             3.079904
Electronics       2.988479
Clothing          2.971429
Beauty            2.872396
Name: Customer Rating, dtype: float64

In [30]:
df.groupby("Month")["Total Sales (INR)"].sum()

Month
April        7334962.92
August       5418893.98
December     6491639.99
February     5416573.21
January      7160788.17
July         7637324.95
June         4992364.75
March        6508879.04
May          6706004.97
November     5578535.08
October      5702923.37
September    6264222.31
Name: Total Sales (INR), dtype: float64

In [31]:
df.groupby("Payment Method")["Total Sales (INR)"].sum()

Payment Method
COD            12457136.55
Credit Card    11155785.99
Debit Card     12142559.04
Net Banking    13219947.52
UPI            12790919.48
Wallet         13446764.16
Name: Total Sales (INR), dtype: float64

In [32]:
df.groupby("Customer Segment")["Total Sales (INR)"].sum()

Customer Segment
Online       25169884.13
Retail       24311192.94
Wholesale    25732035.67
Name: Total Sales (INR), dtype: float64

In [33]:
df.groupby("Discount %")["Total Sales (INR)"].sum()

Discount %
5     4090145.54
6     2601357.99
7     4472626.31
8     2571978.60
9     3013884.87
10    2135668.06
11    2941281.88
12    2203716.23
13    2336372.21
14    2181612.89
15    2379601.14
16    3390797.10
17    2960664.33
18    2154538.58
19    3299050.69
20    2792909.42
21    2916633.13
22    1802171.20
23    2606472.15
24    2405651.47
25    3289021.52
26    2954640.77
27    3434644.08
28    2805072.57
29    2923101.22
30    4549498.79
Name: Total Sales (INR), dtype: float64

In [34]:
df.corr(numeric_only=True)

,Price (INR),Quantity Sold,Total Sales (INR),Customer Rating,Year,Profit (INR),Discount %,Day
Price (INR),1.000000,-0.036321,0.728073,0.008418,0.018077,0.728073,0.000374,-0.023443
Quantity Sold,-0.036321,1.000000,0.569006,-0.015227,0.039692,0.569006,-0.007126,0.111025
Total Sales (INR),0.728073,0.569006,1.000000,-0.004577,0.050927,1.000000,-0.015656,0.049802
Customer Rating,0.008418,-0.015227,-0.004577,1.000000,0.013095,-0.004577,0.014337,-0.068498
Year,0.018077,0.039692,0.050927,0.013095,1.000000,0.050927,0.033975,-0.141257
Profit (INR),0.728073,0.569006,1.000000,-0.004577,0.050927,1.000000,-0.015656,0.049802
Discount %,0.000374,-0.007126,-0.015656,0.014337,0.033975,-0.015656,1.000000,-0.047436
Day,-0.023443,0.111025,0.049802,-0.068498,-0.141257,0.049802,-0.047436,1.000000

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   str
 1   Product Name       1000 non-null   str
 2   Category           1000 non-null   str
 3   Price (INR)        1000 non-null   float64
 4   Quantity Sold      1000 non-null   int64
 5   Total Sales (INR)  1000 non-null   float64
 6   Order Date         1000 non-null   datetime64[us]
 7   Payment Method     1000 non-null   str
 8   Customer Rating    1000 non-null   float64
 9   Month              1000 non-null   str
 10  Year               1000 non-null   int64
 11  Profit (INR)       1000 non-null   float64
 12  Discount %         1000 non-null   int64
 13  Customer Segment   1000 non-null   str
 14  Region             1000 non-null   str
 15  Day                1000 non-null   int32
 16  Month Name         1000 non-null   str
 17  Weekday            1000 non-null   str
dtypes: datetime64[us](1), float64(4), int32(1), int64(3), str(9)
memory usage: 136.8 KB

In [36]:
df.head()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,Profit (INR),Discount %,Customer Segment,Region,Day,Month Name,Weekday
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5,September,2024,19627.824,11,Online,West,12,September,Thursday
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9,December,2024,10204.680,24,Wholesale,North,18,December,Wednesday
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4,May,2024,8873.752,19,Online,South,18,May,Saturday
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2,November,2024,6531.562,15,Online,North,8,November,Friday
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1,December,2024,15954.048,12,Retail,North,27,December,Friday

In [38]:
df.to_csv("flipkart_sales_cleaned.csv", index=False)