In [65]:
import pandas as pd

In [66]:
df = pd.read_csv(r"C:\Users\monika\OneDrive\Desktop\Amazon Sale Report.csv")

In [67]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by,New,PendingS
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,T-shirt,S,On the Way,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False,Easy Ship,NaN,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,3XL,Shipped,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False,Easy Ship,NaN,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True,NaN,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Blazzer,L,On the Way,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False,Easy Ship,NaN,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Trousers,3XL,Shipped,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False,NaN,NaN,NaN

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128976 entries, 0 to 128975
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128976 non-null  int64
 1   Order ID            128976 non-null  str
 2   Date                128976 non-null  str
 3   Status              128976 non-null  str
 4   Fulfilment          128976 non-null  str
 5   Sales Channel       128976 non-null  str
 6   ship-service-level  128976 non-null  str
 7   Category            128976 non-null  str
 8   Size                128976 non-null  str
 9   Courier Status      128976 non-null  str
 10  Qty                 128976 non-null  int64
 11  currency            121176 non-null  str
 12  Amount              121176 non-null  float64
 13  ship-city           128941 non-null  str
 14  ship-state          128941 non-null  str
 15  ship-postal-code    128941 non-null  float64
 16  ship-country        128941 non-null  str
 17  B2B                 128976 non-null  bool
 18  fulfilled-by        39263 non-null   str
 19  New                 0 non-null       float64
 20  PendingS            0 non-null       float64
dtypes: bool(1), float64(4), int64(2), str(14)
memory usage: 19.8 MB

In [69]:
df.isnull() .sum()

index                      0
Order ID                   0
Date                       0
Status                     0
Fulfilment                 0
Sales Channel              0
ship-service-level         0
Category                   0
Size                       0
Courier Status             0
Qty                        0
currency                7800
Amount                  7800
ship-city                 35
ship-state                35
ship-postal-code          35
ship-country              35
B2B                        0
fulfilled-by           89713
New                   128976
PendingS              128976
dtype: int64

In [70]:
df = df.drop(columns=["New", "PendingS"])

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128976 entries, 0 to 128975
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128976 non-null  int64
 1   Order ID            128976 non-null  str
 2   Date                128976 non-null  str
 3   Status              128976 non-null  str
 4   Fulfilment          128976 non-null  str
 5   Sales Channel       128976 non-null  str
 6   ship-service-level  128976 non-null  str
 7   Category            128976 non-null  str
 8   Size                128976 non-null  str
 9   Courier Status      128976 non-null  str
 10  Qty                 128976 non-null  int64
 11  currency            121176 non-null  str
 12  Amount              121176 non-null  float64
 13  ship-city           128941 non-null  str
 14  ship-state          128941 non-null  str
 15  ship-postal-code    128941 non-null  float64
 16  ship-country        128941 non-null  str
 17  B2B                 128976 non-null  bool
 18  fulfilled-by        39263 non-null   str
dtypes: bool(1), float64(2), int64(2), str(14)
memory usage: 17.8 MB

In [72]:
df["fulfilled-by"].value_counts(dropna=False)

fulfilled-by
NaN          89713
Easy Ship    39263
Name: count, dtype: int64

In [73]:
df["currency"].value_counts(dropna=False)

currency
INR    121176
NaN      7800
Name: count, dtype: int64

In [74]:
df["Amount"].value_counts(dropna=False)

Amount
NaN        7800
399.00     5439
771.00     2796
735.00     2436
0.00       2343
           ...
719.05        1
829.52        1
708.58        1
1244.00       1
639.00        1
Name: count, Length: 1409, dtype: int64

In [75]:
df[df["currency"].isnull()].head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,T-shirt,3XL,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,False,NaN
29,29,404-5933402-8801952,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Shirt,3XL,On the Way,0,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,False,Easy Ship
65,65,171-4137548-0481151,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,Shirt,XXL,Cancelled,0,NaN,NaN,Dahod,Gujarat,389151.0,IN,False,NaN
84,84,403-9950518-0349133,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,Shirt,M,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,False,NaN
95,95,405-9112089-3379536,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,Shirt,L,Cancelled,0,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,False,NaN

In [76]:
df[df["Amount"].isnull()]["Status"].value_counts(dropna=False)

Status
Cancelled                       7571
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [77]:
df[(df["Status"] == "Shipped") & (df["Amount"].isnull())].head(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by
938,937,S02-5278980-4327051,04-30-22,Shipped,Amazon,Non-Amazon,Standard,Wallet,Free,Unshipped,15,NaN,NaN,Surat,Gujarat,394210.0,IN,False,NaN
1058,1057,S02-9107114-0460608,04-30-22,Shipped,Amazon,Non-Amazon,Standard,T-shirt,XL,Unshipped,2,NaN,NaN,Surat,Gujarat,394210.0,IN,False,NaN
1616,1615,405-7790745-1369118,04-29-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,M,Cancelled,0,NaN,NaN,RISHIKESH,UTTARAKHAND,249201.0,IN,False,NaN
1990,1989,171-9673855-2321133,04-29-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,S,Cancelled,0,NaN,NaN,DHARUHERA,HARYANA,123106.0,IN,False,NaN
2425,2424,404-7478762-7926753,04-29-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,S,Cancelled,0,NaN,NaN,Gangapur city,Rajshthan,322201.0,IN,False,NaN
2820,2819,404-0814480-8157169,04-29-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Cancelled,0,NaN,NaN,CHENNAI,TAMIL NADU,600091.0,IN,False,NaN
3632,3631,S02-1006261-5356758,04-28-22,Shipped,Amazon,Non-Amazon,Standard,Shirt,L,Unshipped,9,NaN,NaN,Surat,Gujarat,394210.0,IN,False,NaN
3633,3632,S02-3681731-6111841,04-28-22,Shipped,Amazon,Non-Amazon,Standard,Shirt,L,Unshipped,1,NaN,NaN,Surat,Gujarat,394210.0,IN,False,NaN
3635,3634,S02-1926028-4838217,04-28-22,Shipped,Amazon,Non-Amazon,Standard,Shirt,XS,Unshipped,1,NaN,NaN,Surat,Gujarat,394210.0,IN,False,NaN
3637,3636,S02-6828927-1180856,04-28-22,Shipped,Amazon,Non-Amazon,Standard,Shirt,XXL,Unshipped,13,NaN,NaN,Surat,Gujarat,394210.0,IN,False,NaN

In [78]:
df[(df["Amount"].isnull()) & (df["Qty"] > 0)].shape

(124, 19)

In [79]:
df[(df["Amount"].isnull()) & (df["Qty"] > 0)][
    ["Order ID", "Status", "Qty", "Amount", "currency", "Sales Channel"]
].head(20)

                  Order ID     Status  Qty  Amount currency Sales Channel
938    S02-5278980-4327051    Shipped   15     NaN      NaN    Non-Amazon
1058   S02-9107114-0460608    Shipped    2     NaN      NaN    Non-Amazon
3632   S02-1006261-5356758    Shipped    9     NaN      NaN    Non-Amazon
3633   S02-3681731-6111841    Shipped    1     NaN      NaN    Non-Amazon
3635   S02-1926028-4838217    Shipped    1     NaN      NaN    Non-Amazon
3637   S02-6828927-1180856    Shipped   13     NaN      NaN    Non-Amazon
3638   S02-3409426-0744131    Shipped    2     NaN      NaN    Non-Amazon
3887   S02-8357726-8633940    Shipped    1     NaN      NaN    Non-Amazon
3888   S02-6358630-3384547    Shipped    1     NaN      NaN    Non-Amazon
3889   S02-8920429-3367507    Shipped    1     NaN      NaN    Non-Amazon
3890   S02-0827522-8659612    Shipped    1     NaN      NaN    Non-Amazon
3891   S02-7924344-3280541    Shipped    1     NaN      NaN    Non-Amazon
3892   S02-7832149-5714447    Shipped    1     NaN      NaN    Non-Amazon
3893   S02-9649067-3246849    Shipped    1     NaN      NaN    Non-Amazon
3894   S02-2310917-8166336    Shipped    1     NaN      NaN    Non-Amazon
3895   S02-0668744-7285638    Shipped    1     NaN      NaN    Non-Amazon
12975  S02-1862183-4415901  Cancelled    1     NaN      NaN    Non-Amazon
13461  S02-0835825-7267219    Shipped    1     NaN      NaN    Non-Amazon
13717  S02-7568319-2142153    Shipped    1     NaN      NaN    Non-Amazon
13719  S02-9236057-6330320    Shipped    1     NaN      NaN    Non-Amazon

In [80]:
df[df["Sales Channel"] == "Non-Amazon"]["Amount"].isnull().sum()

np.int64(124)

In [81]:
df.duplicated().sum()

np.int64(168)

In [82]:
duplicates = df[df.duplicated()]
duplicates.head(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by
201,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,L,Shipped,1,INR,653.0,CHANDIGARH,CHANDIGARH,160036.0,IN,False,NaN
202,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,S,Shipped,1,INR,399.0,HYDERABAD,TELANGANA,500032.0,IN,False,Easy Ship
203,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,T-shirt,3XL,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,False,NaN
204,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XXL,Shipped,1,INR,363.0,Chennai,TAMIL NADU,600041.0,IN,False,NaN
205,10,407-5633625-6970741,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,S,Shipped,1,INR,685.0,CHENNAI,TAMIL NADU,600073.0,IN,False,NaN
206,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XS,Shipped,1,INR,364.0,NOIDA,UTTAR PRADESH,201303.0,IN,False,NaN
207,12,405-5513694-8146768,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,XS,Shipped,1,INR,399.0,Amravati.,MAHARASHTRA,444606.0,IN,False,Easy Ship
208,13,408-7955685-3083534,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XS,Shipped,1,INR,657.0,MUMBAI,MAHARASHTRA,400053.0,IN,False,NaN
616,539,408-1221783-1443515,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,L,Shipped,1,INR,1112.0,Pune,MAHARASHTRA,411033.0,IN,False,NaN
617,540,404-3977029-4836363,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,T-shirt,L,Cancelled,0,NaN,NaN,MUMBAI,MAHARASHTRA,400042.0,IN,False,NaN

In [83]:
duplicates = df[df.duplicated(keep=False)]
duplicates.shape

(336, 19)

In [84]:
duplicates.head(20)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by
6,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,L,Shipped,1,INR,653.0,CHANDIGARH,CHANDIGARH,160036.0,IN,False,NaN
7,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,S,Shipped,1,INR,399.0,HYDERABAD,TELANGANA,500032.0,IN,False,Easy Ship
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,T-shirt,3XL,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,False,NaN
9,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XXL,Shipped,1,INR,363.0,Chennai,TAMIL NADU,600041.0,IN,False,NaN
10,10,407-5633625-6970741,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,S,Shipped,1,INR,685.0,CHENNAI,TAMIL NADU,600073.0,IN,False,NaN
11,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XS,Shipped,1,INR,364.0,NOIDA,UTTAR PRADESH,201303.0,IN,False,NaN
12,12,405-5513694-8146768,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,XS,Shipped,1,INR,399.0,Amravati.,MAHARASHTRA,444606.0,IN,False,Easy Ship
13,13,408-7955685-3083534,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XS,Shipped,1,INR,657.0,MUMBAI,MAHARASHTRA,400053.0,IN,False,NaN
201,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,L,Shipped,1,INR,653.0,CHANDIGARH,CHANDIGARH,160036.0,IN,False,NaN
202,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,S,Shipped,1,INR,399.0,HYDERABAD,TELANGANA,500032.0,IN,False,Easy Ship
203,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,T-shirt,3XL,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,False,NaN
204,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XXL,Shipped,1,INR,363.0,Chennai,TAMIL NADU,600041.0,IN,False,NaN
205,10,407-5633625-6970741,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,S,Shipped,1,INR,685.0,CHENNAI,TAMIL NADU,600073.0,IN,False,NaN
206,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XS,Shipped,1,INR,364.0,NOIDA,UTTAR PRADESH,201303.0,IN,False,NaN
207,12,405-5513694-8146768,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,XS,Shipped,1,INR,399.0,Amravati.,MAHARASHTRA,444606.0,IN,False,Easy Ship
208,13,408-7955685-3083534,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XS,Shipped,1,INR,657.0,MUMBAI,MAHARASHTRA,400053.0,IN,False,NaN
540,539,408-1221783-1443515,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,L,Shipped,1,INR,1112.0,Pune,MAHARASHTRA,411033.0,IN,False,NaN
541,540,404-3977029-4836363,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,T-shirt,L,Cancelled,0,NaN,NaN,MUMBAI,MAHARASHTRA,400042.0,IN,False,NaN
542,541,406-6993846-8855562,04-30-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XL,Shipped,1,INR,1338.0,ROORKEE,UTTARAKHAND,247667.0,IN,False,NaN
543,542,405-5018129-4536368,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,3XL,Shipped,1,INR,517.0,MANGALURU,KARNATAKA,575006.0,IN,False,NaN

In [85]:
duplicates.iloc[0]

index                                   6
Order ID              408-5748499-6859555
Date                             04-30-22
Status                            Shipped
Fulfilment                         Amazon
Sales Channel                   Amazon.in
ship-service-level              Expedited
Category                          T-shirt
Size                                    L
Courier Status                    Shipped
Qty                                     1
currency                              INR
Amount                              653.0
ship-city                      CHANDIGARH
ship-state                     CHANDIGARH
ship-postal-code                 160036.0
ship-country                           IN
B2B                                 False
fulfilled-by                          NaN
Name: 6, dtype: object

In [86]:
duplicates.iloc[1]

index                                            7
Order ID                       406-7807733-3785945
Date                                      04-30-22
Status                Shipped - Delivered to Buyer
Fulfilment                                Merchant
Sales Channel                            Amazon.in
ship-service-level                        Standard
Category                                     Shirt
Size                                             S
Courier Status                             Shipped
Qty                                              1
currency                                       INR
Amount                                       399.0
ship-city                                HYDERABAD
ship-state                               TELANGANA
ship-postal-code                          500032.0
ship-country                                    IN
B2B                                          False
fulfilled-by                             Easy Ship
Name: 7, dtype: object

In [87]:
duplicates.sort_values("Order ID").head(20)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by
1880,1879,171-0507987-9169958,04-29-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XL,Shipped,1,INR,599.00,AURANGABAD,MAHARASHTRA,431001.0,IN,False,NaN
2098,1879,171-0507987-9169958,04-29-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XL,Shipped,1,INR,599.00,AURANGABAD,MAHARASHTRA,431001.0,IN,False,NaN
6636,6274,171-2630358-5678736,04-26-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,S,Shipped,1,INR,280.00,VIZIANAGARAM,ANDHRA PRADESH,535003.0,IN,False,NaN
6275,6274,171-2630358-5678736,04-26-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,S,Shipped,1,INR,280.00,VIZIANAGARAM,ANDHRA PRADESH,535003.0,IN,False,NaN
6282,6281,171-2918708-7197155,04-26-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Blazzer,XXL,Shipped,1,INR,658.00,PUNE,MAHARASHTRA,412207.0,IN,False,Easy Ship
6643,6281,171-2918708-7197155,04-26-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Blazzer,XXL,Shipped,1,INR,658.00,PUNE,MAHARASHTRA,412207.0,IN,False,Easy Ship
6214,6213,171-3003328-2511523,04-26-22,Cancelled,Merchant,Amazon.in,Standard,T-shirt,XS,On the Way,0,INR,750.48,Pune,MAHARASHTRA,411021.0,IN,False,Easy Ship
6575,6213,171-3003328-2511523,04-26-22,Cancelled,Merchant,Amazon.in,Standard,T-shirt,XS,On the Way,0,INR,750.48,Pune,MAHARASHTRA,411021.0,IN,False,Easy Ship
6012,5705,171-3642547-9981136,04-27-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,3XL,Shipped,1,INR,487.00,MUMBAI,MAHARASHTRA,400064.0,IN,False,NaN
5706,5705,171-3642547-9981136,04-27-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,3XL,Shipped,1,INR,487.00,MUMBAI,MAHARASHTRA,400064.0,IN,False,NaN
6211,6210,171-3995208-9556366,04-26-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,S,Shipped,1,INR,950.00,PANCHKULA,HARYANA,134113.0,IN,False,NaN
6572,6210,171-3995208-9556366,04-26-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,S,Shipped,1,INR,950.00,PANCHKULA,HARYANA,134113.0,IN,False,NaN
4644,4643,171-4480006-2084365,04-27-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XS,Shipped,1,INR,666.00,JAMMU,JAMMU & KASHMIR,180004.0,IN,False,NaN
4956,4643,171-4480006-2084365,04-27-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XS,Shipped,1,INR,666.00,JAMMU,JAMMU & KASHMIR,180004.0,IN,False,NaN
11,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XS,Shipped,1,INR,364.00,NOIDA,UTTAR PRADESH,201303.0,IN,False,NaN
206,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XS,Shipped,1,INR,364.00,NOIDA,UTTAR PRADESH,201303.0,IN,False,NaN
552,551,171-4737030-9245958,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,M,Shipped,1,INR,459.00,Palampur,HIMACHAL PRADESH,176092.0,IN,False,NaN
628,551,171-4737030-9245958,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,M,Shipped,1,INR,459.00,Palampur,HIMACHAL PRADESH,176092.0,IN,False,NaN
6614,6252,171-4777910-3781159,04-26-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,L,Shipped,1,INR,517.00,LUCKNOW,UTTAR PRADESH,226003.0,IN,False,Easy Ship
6253,6252,171-4777910-3781159,04-26-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,L,Shipped,1,INR,517.00,LUCKNOW,UTTAR PRADESH,226003.0,IN,False,Easy Ship

In [88]:
df = df.drop_duplicates()

In [89]:
df.duplicated() .sum()

np.int64(0)

In [90]:
df.info()

<class 'pandas.DataFrame'>
Index: 128808 entries, 0 to 128975
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128808 non-null  int64
 1   Order ID            128808 non-null  str
 2   Date                128808 non-null  str
 3   Status              128808 non-null  str
 4   Fulfilment          128808 non-null  str
 5   Sales Channel       128808 non-null  str
 6   ship-service-level  128808 non-null  str
 7   Category            128808 non-null  str
 8   Size                128808 non-null  str
 9   Courier Status      128808 non-null  str
 10  Qty                 128808 non-null  int64
 11  currency            121019 non-null  str
 12  Amount              121019 non-null  float64
 13  ship-city           128775 non-null  str
 14  ship-state          128775 non-null  str
 15  ship-postal-code    128775 non-null  float64
 16  ship-country        128775 non-null  str
 17  B2B                 128808 non-null  bool
 18  fulfilled-by        39213 non-null   str
dtypes: bool(1), float64(2), int64(2), str(14)
memory usage: 18.8 MB

In [91]:
df["Date"] = pd.to_datetime(df["Date"])

C:\Users\monika\AppData\Local\Temp\ipykernel_10568\936118274.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"])

In [92]:
df["Date"] = pd.to_datetime(df["Date"], format="%m-%d-%y")

In [93]:
df.info()

<class 'pandas.DataFrame'>
Index: 128808 entries, 0 to 128975
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128808 non-null  int64
 1   Order ID            128808 non-null  str
 2   Date                128808 non-null  datetime64[us]
 3   Status              128808 non-null  str
 4   Fulfilment          128808 non-null  str
 5   Sales Channel       128808 non-null  str
 6   ship-service-level  128808 non-null  str
 7   Category            128808 non-null  str
 8   Size                128808 non-null  str
 9   Courier Status      128808 non-null  str
 10  Qty                 128808 non-null  int64
 11  currency            121019 non-null  str
 12  Amount              121019 non-null  float64
 13  ship-city           128775 non-null  str
 14  ship-state          128775 non-null  str
 15  ship-postal-code    128775 non-null  float64
 16  ship-country        128775 non-null  str
 17  B2B                 128808 non-null  bool
 18  fulfilled-by        39213 non-null   str
dtypes: bool(1), datetime64[us](1), float64(2), int64(2), str(13)
memory usage: 18.8 MB

In [94]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month_name()
df["Month No"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.day_name()

In [95]:
df.info()

<class 'pandas.DataFrame'>
Index: 128808 entries, 0 to 128975
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128808 non-null  int64
 1   Order ID            128808 non-null  str
 2   Date                128808 non-null  datetime64[us]
 3   Status              128808 non-null  str
 4   Fulfilment          128808 non-null  str
 5   Sales Channel       128808 non-null  str
 6   ship-service-level  128808 non-null  str
 7   Category            128808 non-null  str
 8   Size                128808 non-null  str
 9   Courier Status      128808 non-null  str
 10  Qty                 128808 non-null  int64
 11  currency            121019 non-null  str
 12  Amount              121019 non-null  float64
 13  ship-city           128775 non-null  str
 14  ship-state          128775 non-null  str
 15  ship-postal-code    128775 non-null  float64
 16  ship-country        128775 non-null  str
 17  B2B                 128808 non-null  bool
 18  fulfilled-by        39213 non-null   str
 19  Year                128808 non-null  int32
 20  Month               128808 non-null  str
 21  Month No            128808 non-null  int32
 22  Day                 128808 non-null  int32
 23  Weekday             128808 non-null  str
dtypes: bool(1), datetime64[us](1), float64(2), int32(3), int64(2), str(15)
memory usage: 22.2 MB

In [96]:
df[["Date","Year","Month","Month No","Day","Weekday"]].head()

        Date  Year  Month  Month No  Day   Weekday
0 2022-04-30  2022  April         4   30  Saturday
1 2022-04-30  2022  April         4   30  Saturday
2 2022-04-30  2022  April         4   30  Saturday
3 2022-04-30  2022  April         4   30  Saturday
4 2022-04-30  2022  April         4   30  Saturday

In [97]:
df["Amount"].describe()

count    121019.000000
mean        648.631921
std         281.224583
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [98]:
df[df["Amount"] == 0][["Order ID","Status","Qty","Category","Sales Channel"]].head(20)

,Order ID,Status,Qty,Category,Sales Channel
213,408-4547464-4180323,Shipped - Delivered to Buyer,1,Shirt,Amazon.in
375,408-5020509-5674715,Shipped - Returned to Seller,1,Blazzer,Amazon.in
386,408-3137526-3167563,Shipped,1,Shirt,Amazon.in
389,408-7971979-8745937,Shipped - Delivered to Buyer,1,Blazzer,Amazon.in
393,408-0912805-7526753,Shipped,1,T-shirt,Amazon.in
437,408-6466311-6949931,Shipped,1,T-shirt,Amazon.in
442,408-6732772-4525113,Shipped - Delivered to Buyer,1,T-shirt,Amazon.in
447,408-7937211-8974712,Shipped,1,T-shirt,Amazon.in
450,408-6348199-2089932,Shipped,1,T-shirt,Amazon.in
730,408-4193711-8156307,Shipped - Delivered to Buyer,1,Wallet,Amazon.in
732,408-0902233-8069950,Shipped - Returned to Seller,1,Shirt,Amazon.in
828,408-9407260-0749114,Shipped,1,Shirt,Amazon.in
845,408-5118229-6373917,Shipped,1,Shirt,Amazon.in
931,408-6069754-7397924,Shipped,1,Shirt,Amazon.in
948,408-8489677-5577933,Shipped - Delivered to Buyer,1,Shirt,Amazon.in
987,408-2548158-8811519,Shipped - Delivered to Buyer,1,T-shirt,Amazon.in
1072,408-0466342-6160313,Shipped,1,Blazzer,Amazon.in
1105,408-3011835-7100318,Shipped - Delivered to Buyer,1,Shirt,Amazon.in
1116,408-7721306-8516366,Shipped,1,Shirt,Amazon.in
1227,408-5393823-3123507,Shipped - Delivered to Buyer,1,Shirt,Amazon.in

In [99]:
(df["Amount"] == 0).sum()

np.int64(2340)

In [100]:
df[df["Amount"] == 0]["Category"].value_counts()

Category
T-shirt     1012
Shirt        856
Blazzer      231
Trousers     174
Perfume       32
Wallet        22
Socks         12
Shoes          1
Name: count, dtype: int64

In [101]:
df[df["Amount"] == 0]["Fulfilment"].value_counts()

Fulfilment
Amazon      1527
Merchant     813
Name: count, dtype: int64

In [102]:
df[df["Amount"] == 0]["Courier Status"].value_counts()

Courier Status
Shipped      2314
Unshipped      26
Name: count, dtype: int64

In [103]:
df.to_csv("Amazon_Cleaned.csv", index=False)

In [104]:
df.shape

(128808, 24)

In [105]:
df["Amount"].sum()

np.float64(78496786.39)

In [106]:
df.groupby("Category")["Order ID"].nunique().sort_values(ascending=False)

Category
T-shirt     47782
Shirt       46499
Blazzer     14984
Trousers    10141
Perfume      1146
Wallet        897
Socks         409
Shoes         144
Watch           2
Name: Order ID, dtype: int64

In [107]:
df.groupby("Category")["Amount"].sum().sort_values(ascending=False)

Category
T-shirt     39154132.17
Shirt       21269768.70
Blazzer     11208506.12
Trousers     5341305.30
Perfume       789419.66
Wallet        458408.18
Socks         150397.50
Shoes         123933.76
Watch            915.00
Name: Amount, dtype: float64

In [108]:
df["Category"].value_counts()

Category
T-shirt     50219
Shirt       49804
Blazzer     15489
Trousers    10607
Perfume      1157
Wallet        926
Socks         439
Shoes         164
Watch           3
Name: count, dtype: int64

In [109]:
df.groupby("ship-state")["Amount"].sum().sort_values(ascending=False).head(10)

ship-state
MAHARASHTRA       13318966.38
KARNATAKA         10465387.03
TELANGANA          6909670.08
UTTAR PRADESH      6814126.08
TAMIL NADU         6510503.73
DELHI              4228503.97
KERALA             3821997.58
WEST BENGAL        3503223.44
ANDHRA PRADESH     3214859.86
HARYANA            2879146.99
Name: Amount, dtype: float64

In [110]:
df.groupby("ship-city")["Amount"].sum().sort_values(ascending=False).head(10)

ship-city
BENGALURU    6836614.65
HYDERABAD    4941790.25
MUMBAI       3696704.04
NEW DELHI    3608277.78
CHENNAI      3098745.74
PUNE         2337978.18
KOLKATA      1412815.87
GURUGRAM     1220562.74
THANE        1003878.29
LUCKNOW       933926.34
Name: Amount, dtype: float64

In [111]:
df.groupby("Status")["Amount"].sum().sort_values(ascending=False)

Status
Shipped                          50268420.00
Shipped - Delivered to Buyer     18619610.00
Cancelled                         6910831.39
Shipped - Returned to Seller      1269245.00
Shipped - Picked Up                661252.00
Pending                            430271.00
Pending - Waiting for Pick Up      192138.00
Shipped - Returning to Seller      107620.00
Shipped - Out for Delivery          26971.00
Shipped - Rejected by Buyer          7295.00
Shipped - Lost in Transit            1997.00
Shipped - Damaged                    1136.00
Shipping                                0.00
Name: Amount, dtype: float64

In [112]:
df.groupby("Fulfilment")["Amount"].sum().sort_values(ascending=False)

Fulfilment
Amazon      54262165.00
Merchant    24234621.39
Name: Amount, dtype: float64

In [113]:
df["Fulfilment"].value_counts()

Fulfilment
Amazon      89595
Merchant    39213
Name: count, dtype: int64

In [114]:
df.groupby("Sales Channel")["Amount"].sum()

Sales Channel
Amazon.in     78496786.39
Non-Amazon           0.00
Name: Amount, dtype: float64

In [115]:
df["Sales Channel"].value_counts()

Sales Channel
Amazon.in     128684
Non-Amazon       124
Name: count, dtype: int64

In [116]:

df.groupby("B2B")["Amount"].sum()

B2B
False    77905565.60
True       591220.79
Name: Amount, dtype: float64

In [117]:
df["B2B"].value_counts()

B2B
False    127937
True        871
Name: count, dtype: int64

In [118]:
df.groupby("Courier Status")["Amount"].sum().sort_values(ascending=False)

Courier Status
Shipped       70971225.00
Unshipped      4339691.00
On the Way     3185870.39
Cancelled            0.00
Name: Amount, dtype: float64

In [119]:
df.to_csv("Amazon_Cleaned.csv", index=False)

In [120]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\monika
['.android', '.AndroidStudio2.2', '.AndroidStudio2.3', '.AndroidStudio3.1', '.AndroidStudioPreview3.0', '.gradle', '.ipynb_checkpoints', '.ipython', '.jupyter', '.python_history', '3D Objects', 'Amazon_Cleaned.csv', 'Amazon_Cleaned.xlsx', 'Amazon_data_cleaning.ipynb', 'AndroidStudioProjects', 'AppData', 'Application Data', 'bootcamp1.ipynb', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'Favorites', 'learning python basic .ipynb', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.0.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.1.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.2.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'products.xml', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'sonal_trial.ipynb', 'Start Menu', 'Templates', 'Tracing', 'Untitled.ipynb', 'Videos']